### ISSUE TITLE
Be more friendly in your conclusions

### ISSUE THREAD

**Issue by lebedec** [Speak2Erase/fmod-oxide#4]
Hi! In your project README I found summary about my crate:

> libfmod is automatically generated from the FMOD documentation and is full of mistakes. (Wrong parameter types in functions, accepting &str instead of &[u8], etc) It also does not provide an abstraction over userdata or callbacks.

It is an incorrect summary actually =) 

1. It can't provide an abstraction over callbacks or void pointers (userdata) because it impossible. We must use C interfaces to implement FFI, there is no other way.
2. It generated from FMOD SDK API headers. And fix some "FMOD team mistakes" by parsing documentation additionally (for example, there is no way to determine by pointer definition is it out parameter or array)
3. Yep, it has bugs, but it maintained properly enough. All new bugs fixed. 

For me it looks like you underestimated the complexity of work done. And without sufficient understanding you make false conclusions. Main feature of libfmod project is generation. It is huge cost reducer for support multiple releases of FMOD. I think you will feel it when you start working on support FMOD 2.03 for your crate. 

I suggest correct this to more friendly summary =) Let's support each other, if not with commits, then at least with a kind words =) Who knows, maybe in the future one of us will help another.

**Comment by Speak2Erase** [comment]
I'm sorry that my words were harsh and unfair- when I wrote them it was just after I had a bad experience with your crate.
I'll update the README and yank the versions on crates.io.

**Comment by lebedec** [comment]
Thank you!
